name: ClearGoose
main: bishan.cleargoose.ClearGoose
version: 0.0.1
description: Lag was never an option
author: bishan_

commands:
  clearitems:
    description: Clears lag
    usage: /clearitems [n] [seconds/minutes]
    permission: ClearGoose.op
    permission-message: You don't have <permission>
